### ISSUE TITLE
新版本在linux上使用报错

### ISSUE THREAD

**Issue by ZXTFINAL** [SeanLee97/xmnlp#31]
Traceback (most recent call last):
  File "normal_keywords.py", line 49, in <module>
    keywords_list += xmnlp.seg(text)
  File "/home/ubuser/anaconda3/envs/gpu/lib/python3.8/site-packages/xmnlp/lexical/__init__.py", line 53, in seg
    load_lexical()
  File "/home/ubuser/anaconda3/envs/gpu/lib/python3.8/site-packages/xmnlp/lexical/__init__.py", line 46, in load_lexical
    lexical = LexicalDecoder(
  File "/home/ubuser/anaconda3/envs/gpu/lib/python3.8/site-packages/xmnlp/lexical/lexical_model.py", line 45, in __init__
    self.lexical_model = LexicalModel(os.path.join(model_dir, 'lexical.onnx'))
  File "/home/ubuser/anaconda3/envs/gpu/lib/python3.8/site-packages/xmnlp/base_model.py", line 11, in __init__
    self.sess = ort.InferenceSession(model_path, providers=['CPUExecutionProvider'])
  File "/home/ubuser/anaconda3/envs/gpu/lib/python3.8/site-packages/onnxruntime/capi/session.py", line 158, in __init__
    self._load_model(providers or [])
  File "/home/ubuser/anaconda3/envs/gpu/lib/python3.8/site-packages/onnxruntime/capi/session.py", line 177, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node:Embedding-Token/NotEqual : No Op registered for Equal with domain_version of 13

**Comment by SeanLee97** [comment]
我在我的 linux & mac 机器 + python38 环境上是可以跑的，不太确定是否是 gpu 环境原因，明天确认下。

**Comment by SeanLee97** [comment]
hi，我在我的 linux 机器上是可以跑的，我怀疑是 onnxruntime 版本的问题，可否提供一下你安装的版本号？
```bash
$ pip list | grep "onnxruntime"
onnxruntime        1.9.0
```

**Comment by SeanLee97** [comment]
先关闭了，有问题再 reopen
